### ISSUE TITLE
Fix the SonarCloud issues in IForwardSover

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#102]
The IForwardSolver interface is not correctly organized and as a result, it causes code issues. When this file is inherited these issues are duplicated in the new class. 

Fix the organization in the main file and then in the classes that inherit IForwardSolver.

**Comment by hayakawa16** [comment]
Thanks for working on this!

**Comment by dcuccia** [comment]
Can you describe how they are currently organized, and how you plan to change it?

**Comment by lmalenfant** [comment]
> Can you describe how they are currently organized, what the code issues are, and how you plan to change it?

Overloads of methods are supposed to be organized together in a class, We are updating the XML comments with what previously were comments in the file and putting the methods together.

Once it is complete, I will make sure you are both included in the PR so you can comment on the changes.
