### ISSUE TITLE
Bug in 2 of the Detectors TransmittedMTOfXAndYAndSubregionHistDetector and ReflectedMTOfXAndYAndSubregionHistDetector

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#115]
**Describe the bug**
While looking though the serialization code to research the reconfiguration, I discovered a bug in two of the detectors. This could result in the wrong information being serialized or it could cause an exception if the data does not align. 

**Application (MCCL, MATLAB or VTS code):**
VTS Code

**Bug Locations**
VTS\src\Vts\MonteCarlo\Detectors\
File: TransmittedMTOfXAndYAndSubregionHistDetector.cs at line 342, this value should be Y
File: ReflectedMTOfXAndYAndSubregionHistDetector.cs at line 345, this value should be Y

**Additional context**
This should be fixed as a hotfix before the next release because it could produce unexpected results.

**Comment by lmalenfant** [comment]
@hayakawa16 could you update the unit tests for these detectors so in future if there was a bug, they would fail.

**Comment by hayakawa16** [comment]
Unit tests updated and run successfully.
