### ISSUE TITLE
Move the FemModeling and MGRTE into a separate repository

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#126]
Two years ago we moved the MGRTE code out of the VTS and into a separate library because it was not being used in any of our software, we put a note in the release notes in case it was being used externally to notify users that we could create a separate NuGet package. It seems that this code is not being used.

This issue is to move out the Vts.FemModeling code and the MGRTE console application from the main VTS repo and put it in a separate repository. @janakarana let us know if you foresee any issues with us making this change.

**Comment by janakarana** [comment]
I  don't see any issues.  You can put it in a separate repository.

**Comment by lmalenfant** [comment]
@janakarana I added the repository https://github.com/VirtualPhotonics/Vts.FemModeling

When you have time, could you clone the repo and make sure everything is there. The feature branch for this issue will have the changes to the Vts to remove Vts.FemModeling.
