### ISSUE TITLE
Fixes for Mac Getting Started page

### ISSUE THREAD

**Issue by scottprahl** [VirtualPhotonics/VTS#138]
Trying to install `vts` on a new M3 Macbook and ran into a few dated recommendations on the getting started page

    https://github.com/VirtualPhotonics/VTS/wiki/Getting-Started-on-Mac

First, bump the recommended version of .NET from 5 is 6.  It seems the project already uses version 6 since some tests during build require this version.  (Other advantages are that version 5 is EOL and version 6 has both x86 and amd binaries)

Second, update the `brew` command to install `powershell`. Newer versions of `brew` require the directive 'cask' to be omitted.  Change to

    brew install powershell
    pwsh

**Comment by hayakawa16** [comment]
Thanks for your recommendations!  You are correct, we are on .NET 6.  I will update the Getting Started page for Mac.  We don't have any team members that regularly run on Mac so your comments are very appreciated!

**Comment by janakarana** [comment]
Thanks for bringing this to our attention.  'cask' was omitted.
```
brew install powershell
pwsh
```

**Comment by hayakawa16** [comment]
Since @janakarana checked this out, I plan to update this page too:
https://github.com/VirtualPhotonics/Vts.MonteCarlo/wiki/Getting-Started-on-Mac
