### ISSUE TITLE
Address deprecation warning when building `vts` under .NET v6

### ISSUE THREAD

**Issue by scottprahl** [VirtualPhotonics/VTS#139]
When building `vts` under .NET v6  I see

    /Users/prahl/Documents/Code/git/vts/src/Vts/Range/RangeOfT.cs(132,50): warning CS0618: 
    'Range<T>.AsEnumerable()' is obsolete: 'This method is deprecated. Use built-in IEnumerable implementation 
    instead.' [/Users/prahl/Documents/Code/git/vts/src/Vts/Vts.csproj]

**Comment by hayakawa16** [comment]
This should be just a warning and not an error.  When we remove a *public* class, we mark it as obsolete prior to removing it so that users have a chance to modify their code.  Thanks for pointing that out so we can document our process.
