### ISSUE TITLE
Updates to PowerShell scripts for building zip files

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#148]
Add a PowerShell script to create zip files with the VTS dlls so they can be utilized in the Python scripting project.

Build a zip file for each platform, Windows, Linux and Mac.

Change the other scripts to accommodate this new script and make sure scripts can run independently.

**Comment by dcuccia** [comment]
Would it be feasible to use Nuget programmatically via pythonnet instead?

**Comment by dcuccia** [comment]
Assuming the .Net SDK is installed, [this](https://learn.microsoft.com/en-us/nuget/consume-packages/install-use-packages-dotnet-cli) could work.

**Comment by lmalenfant** [comment]
It works for the CSharp scripts but both Scott Prahl and tried for the Python scripts and were unsuccessful, see this thread https://github.com/VirtualPhotonics/Vts.Scripting.Python/issues/6

**Comment by dcuccia** [comment]
I see, interesting. Would love to have a hands-off way of using nuget, so that there aren't additional/separate packaging strategies across the different use cases. I might have time to look at this over the weekend, if that's of interest.

**Comment by lmalenfant** [comment]
That would be great! This has been an open issue on the Python scripting repo since it was created. NuGet worked great for CSharp but not Python.

**Comment by dcuccia** [comment]
Sorry a little slow, but made some progress over the weekend. Will update soon.
