### ISSUE TITLE
Monte Carlo two region tissue with refractive index mismatch

### ISSUE THREAD

**Issue by hayakawa16** [VirtualPhotonics/VTS#17]
I am interested in running simulations in which an ellipsoid (or other tissue region) inclusion has a different refractive index than the surrounding tissue.

I have started a branch named ch-190214-tissue-inclusion-diff-n to begin making changes.

**Comment by hayakawa16** [comment]
I restarted branch and renamed to ch-190302-tissue-inclusion-diff-n.

**Comment by dcuccia** [comment]
I see that there were changes to this [and other long-running branches](https://github.com/VirtualPhotonics/VTS/branches) as recently as May 2023. Would it be worth a review of how we can bring these changes into the main branch?

**Comment by hayakawa16** [comment]
This is the branch I work on the most because it involves work I do for my research.  The reason I didn't feel ready to merge into master is because I wasn't sure the impact to timing with these code changes.  Lisa has since written Benchmark code that allowed me to run a simulation on master and then run the same simulation on my branch and compare the timing.  Very little difference between the two so I am confident now of merging it in.  Another hesitation was that I don't think I have the code written to reflect/refract for *all* internal tissue regions.  I don't think this is a reason not to merge to master though. 

I like your idea of a review.

**Comment by dcuccia** [comment]
Got it. Perhaps long-term we can have any "long-running branches" as forks of the repository (using nice built-in features of GitHub).

The benchmarks are really important, and I think we can/should expand them if we ever want to work on performance-related changes. Great to hear they're similar on the branch.

Do you have any thoughts on the prep work involved to do a review of the handful of long-running branches out there? Similar to comments elsewhere, I'm not looking to create a bunch of immediate work for the team, just thinking about how we can slowly migrate to small features/fixes and have most work happen off "master".
