### ISSUE TITLE
Preparation for the October Release

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#172]
This issue will is a placeholder for the October release, we will create a branch to update the version numbers and create the next VTS release.

**Comment by hayakawa16** [comment]
I pulled the branch code and ran BuildTestReleaseMCCL.  It created a zip for Linux, Mac and Win.  I ran geninfiles, then the sample infile, then post-processed with Octave.  
I thought possibly there might be a single zip here too.  I'm still getting the hang of this uni-platform stuff.
I think the key change is a single zip for the Scripting.  So I ran BuildTestRelease and created a VTS_Scripting_v12.0.0.zip. When I unzipped, there were just dlls and Vts.pdb, Vts.xml.  Not sure what to do next to test.
