### ISSUE TITLE
PowerShell script BuildTestReleaseMATLAB throws an error

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#180]
**Describe the bug**
I cloned a clean VTS copy and selected the master branch updated on Oct 2, 2024. When I used ./BuildTestReleaseMATLAB, the MATLAB release generation was stopped after opening the MATLAB. The MATLAB error was
Running unit tests for Monte Carlo simulations...
Unable to resolve the name 'Vts.MonteCarlo.Detectors.ROfRhoDetectorInput'.

Error in DetectorInput.ROfRho (line 175)
            sampleInput = Vts.MonteCarlo.Detectors.ROfRhoDetectorInput;

Error in mc_tests (line 5)
si = SimulationInput();

Error in vts_tests (line 10)
mc_tests();

However, when I checked an earlier date (Sep 17,2024  Merge pull request #171...), I was able to generate a MATLAB release without any problems.

**Application (MCCL, MATLAB or VTS code):**
MATLAB

**To Reproduce**
1. Clone the VTS
2. In the VTS folder select the file BuildTestReleaseMATLAB.ps1
4. Right-click and select Run with PowerShell
5. See error

**Expected behavior**
The MATLAB tests should run and a zip file is created

**Comment by lmalenfant** [comment]
@janakarana this was what Carole described and what you alerted to us previously. The libraries were not being copied to the MATLAB folder because win-x64 is only created when running BuildTestRelease, if BuildTestReleaseMATLAB is run in isolation then it needs to pull those libraries from local. I made the change on the branch, could you pull this version and if it fixes you issue, I will merge into master.

**Comment by janakarana** [comment]
@lmalenfant I pulled the code and ran BuildTestReleaseMATLAB. I created the release without any errors. Thank you

**Comment by lmalenfant** [comment]
@janakarana if you approve the PR I can merge it.
