### ISSUE TITLE
Monte Carlo Post Processor addition of "inpath" option

### ISSUE THREAD

**Issue by hayakawa16** [VirtualPhotonics/VTS#22]
The MC Post Processor (MCPP) infile specifies an InputFolder that designates where the database to be post-processed resides.  The code was written so that the location of the InputFolder needs to reside within the MCCL download folder.

Add command line option "inpath" that would enable the user to overwrite the InputFolder and specify an absolute path.  Note an "outpath" which specifies the location of the results of the MCPP already exists.

**Comment by hayakawa16** [comment]
Fix is in Monte Carlo Command Line Application 4.8 Beta

**Comment by hayakawa16** [comment]
Fix had a bug in it.  Problem occurs in PostProcessorInputValidation.cs where the code checks for the existence of the input folder and only uses the infile for this information.

**Comment by hayakawa16** [comment]
To fix this bug I added the "inpath" string as a parameter to PostProcessorSetup.ValidatePostProcessorInput so that the inpath string could be combined with the input file InputFolder to determine whether the files and database exist and can be post-processed.

**Comment by dcuccia** [comment]
@hayakawa16 sounds like this is done and can be closed?

**Comment by hayakawa16** [comment]
Yes.
