### ISSUE TITLE
24 bugs in ParallelMonteCarloSimulation.cs

### ISSUE THREAD

**Issue by lmalenfant** [VirtualPhotonics/VTS#79]
**Describe the bug**
In the file ParallelMonteCarloSimulation.cs 'listOfMeans.FirstOrDefault()' is null on at least one execution path. There are 24 instances of this bug identified by SonarCloud in this file.

**Application (VTS code):**

**To Reproduce**
The link to the issues is here:
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=VirtualPhotonics_VTS&open=AYmYDtRnMpwhnU9-85fg

**Expected behavior**
Avoid the code throwing a NullReferenceException unexpectedly.

**Additional context**
The resolution and why this is an issue is detailed on SonarCloud at the link above.

**Comment by lmalenfant** [comment]
@hayakawa16 I assigned this one to you because you mentioned that you would like to fix this but let me know if you need any assistance.

**Comment by lmalenfant** [comment]
I ran SonarCloud on the branch and the bugs are still there, there are 28 bugs now though, possibly these were already present but not detected.
https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=VirtualPhotonics_VTS

**Comment by hayakawa16** [comment]
All looks great by me!
