### ISSUE TITLE
Mie Scattering Error

### ISSUE THREAD

**Issue by Venki-Kavuri** [VirtualPhotonics/VTS#8]
When I tried using 'MieScattering' instead of 'PowerLaw' I am getting the following error. Could you please help me with the error?

Thanks,

Error using Vts.SpectralMapping.MieScatterer
No constructor 'Vts.SpectralMapping.MieScatterer' with matching signature found.

Error in VtsSpectroscopy.GetOP (line 43)
                        scattererNET = Vts.SpectralMapping.MieScatterer(...

Error in vts_solver_demo (line 111)
op = VtsSpectroscopy.GetOP(absorbers, scatterer, wv);

**Comment by hayakawa16** [comment]
Hi,
It would be helpful to see the exact code that caused this error.  Did you follow the example in vts_solver_demo.m of how to set the parameters if you'd like to use Mie?  For example, look around line 95, it has been commented out, but it it gives an example of what you need to set if you use a Mie scatterer option.  If you feel you're setting the parameters correctly, please paste in code that I can run and debug.
Thanks!
Carole

**Comment by dcuccia** [comment]
Closeable?

**Comment by hayakawa16** [comment]
Yes.
